# docker compose up --build
services:
    postgres:
        image: postgres:16
        container_name: postgres-db
        restart: unless-stopped
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: sqldropbox
        volumes:
            - postgres_data:/var/lib/postgresql/data
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U postgres"]
            interval: 5s
            timeout: 5s
            retries: 10

        networks:
            - appnet

    api:
        build:
            context: ./sql-dropbox-backend
            dockerfile: Dockerfile
        volumes:
            - ./keys:/run/keys:ro
        env_file:
            - backend.prod.env
        container_name: dotnet-api
        restart: unless-stopped
        ports:
            - "8080:8080"
        environment:
            ASPNETCORE_ENVIRONMENT: Production
            ASPNETCORE_URLS: "http://+:8080"
            ConnectionStrings__DefaultConnection: ${DB_CONNECTION}
            Password__Salt: ${PASSWORD_SALT}
            Password__Pepper: ${PASSWORD_PEPPER}
            Jwt__Issuer: ${JWT_ISSUER}
            Jwt__Audience: ${JWT_AUDIENCE}
            Jwt__AccessTokenMinutes: ${JWT_ACCESS_TOKEN_MINUTES}
            Jwt__RefreshTokenDays: ${JWT_REFRESH_TOKEN_DAYS}
            AllowedOrigins: ${ALLOWED_ORIGINS}
        networks:
            - appnet

    frontend:
        build:
            context: ./sql-dropbox-frontend
            dockerfile: Dockerfile
            args:
                NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}
        env_file:
            - frontend.prod.env
        container_name: nextjs-app
        restart: unless-stopped
        depends_on:
            - api
        ports:
            - "3000:3000"
        environment:
            NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}
            JWT_PUBLIC_KEY: ${JWT_PUBLIC_KEY}
        networks:
            - appnet

volumes:
    postgres_data:

networks:
    appnet:
        driver: bridge
